package com.nursultan.cryptoapp.pojo

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName
@Entity(tableName = "fav_coin_price_info_table")
class FavCoinPriceInfo(
    type: String? = null,
    market: String? = null,
    fromsymbol: String,
    tosymbol: String? = null,
    flags: String? = null,
    price: Double? = null,
    lastupdate: Long? = null,
    median: Double? = null,
    lastvolume: Double? = null,
    lastvolumeto: Double? = null,
    lasttradeid: String? = null,
    volumeday: Double? = null,
    volumedayto: Double? = null,
    volume24hour: Double? = null,
    volume24hourto: Double? = null,
    openday: Double? = null,
    highday: Double? = null,
    lowday: Double? = null,
    open24hour: Double? = null,
    higH24hour: Double? = null,
    low24hour: Double? = null,
    lastmarket: String? = null,
    holumehour: Double? = null,
    volumehourto: Double? = null,
    openhour: Double? = null,
    highhour: Double? = null,
    lowhour: Double? = null,
    toptiervolume24hour: Double? = null,
    toptiervolume24hourto: Double? = null,
    change24hour: Double? = null,
    changepct24hour: Double? = null,
    changeday: Double? = null,
    changepctday: Double? = null,
    changehour: Double? = null,
    changepcthour: Double? = null,
    conversiontype: String? = null,
    conversionsymbol: String? = null,
    supply: Int? = null,
    mktcap: Double? = null,
    mktcappenalty: Int? = null,
    totalvolume24h: Double? = null,
    totalvolume24hto: Double? = null,
    totaltoptiervolume24h: Double? = null,
    totaltoptiervolume24hto: Double? = null,
    imageUrl: String? = null

) : CoinPriceInfo(
    type,
    market,
    fromsymbol,
    tosymbol,
    flags,
    price,
    lastupdate,
    median,
    lastvolume,
    lastvolumeto,
    lasttradeid,
    volumeday,
    volumedayto,
    volume24hour,
    volume24hourto,
    openday,
    highday,
    lowday,
    open24hour,
    higH24hour,
    low24hour,
    lastmarket,
    holumehour,
    volumehourto,
    openhour,
    highhour,
    lowhour,
    toptiervolume24hour,
    toptiervolume24hourto,
    change24hour,
    changepct24hour,
    changeday,
    changepctday,
    changehour,
    changepcthour,
    conversiontype,
    conversionsymbol,
    supply,
    mktcap,
    mktcappenalty,
    totalvolume24h,
    totalvolume24hto,
    totaltoptiervolume24h,
    totaltoptiervolume24hto,
    imageUrl

) {
}